import { Dispatch } from 'react'

export type ActionType =
  | 'prime'
  | 'catalog updated'
  | 'geointerests updated'
  | 'site selected'
  | 'product selected'
  | 'flavor selected'
  | 'cycle site'
  | 'cycle product'
  | 'cycle flavor'
  | 'map center changed'
  | 'map moved'
  | 'make current site intended'
  | 'pointer moved'
  | 'pointer left map'
  | 'animation tick'
  | 'toggle animation'
  | 'tick clicked'
  | 'tick forward'
  | 'tick backward'
  | 'product load update'

export type ObserverDispatch = Dispatch<{ type: ActionType, payload?: unknown }>
