[package]
name = "raster_to_json"
version = "0.1.0"
authors = ["Atte Hinkka <atte.hinkka@iki.fi>"]
edition = "2018"

[dependencies]
gdal = "0.10.0"
gdal-sys = { version = "0.4.0", features = ["bindgen"] }
serde_json = "1.0.68"
